### ISSUE TITLE
Capital letters in extensions cause a problem (caused duplicate file extensions via FileZilla)

### ISSUE THREAD

**Issue by omnignorant** [PermanentOrg/sftp-service#95]
On upload, a file named `DSC_0003.JPG` will be renamed `DSC_0003.JPG.JPG`

![Screenshot 2023-03-01 at 3 35 55 PM](https://user-images.githubusercontent.com/6335874/222280767-2546a5cc-a043-4fa4-80d8-6cde660166b8.png)
![Screenshot 2023-03-01 at 3 39 54 PM](https://user-images.githubusercontent.com/6335874/222280794-720b6f9e-3c0c-4674-90fd-aebf79968603.png)

**Comment by slifty** [comment]
I can confirm that if the extension ends in capitalized letters the the downloadname script doesn't properly capture it as an extension.

e.g. 

`test.TXT` is given the downloadname `test.TXT.TXT`

**Comment by omnignorant** [comment]
awesome, thanks!

**Comment by Fenn-CS** [comment]
Update 

https://github.com/PermanentOrg/back-end/issues/424#issuecomment-1455885536

**Comment by slifty** [comment]
@Fenn-CS Thank you for digging into this; interesting.

On the one hand I could have the sftp service strip the extension when defining the `displayName` but on the other hand that would cause an issue when the file is named `thing.txt.txt` since both extensions would be stripped.

I think we need to modify the displayName logic in order to be consistent: it should either always or never strip the extension.  cc @cecilia-donnelly

**Comment by cecilia-donnelly** [comment]
I agree with @slifty , that seems like a straightforward bug in `displayName`. If we're stripping extensions then let's strip extensions!

**Comment by slifty** [comment]
I believe this is resolved, now that we have updated the downloadName script.
